version: '3'

services:
  neo:
    container_name: dbneo
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: none
    ports:
      - 11102:7687
      - 8100:7474

  mongo:
    container_name: dbmongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: g)2gH4G)4(3(
    #ports:
    #  - 11101:27017

  mongo-express:
    container_name: mongoWeb
    image: mongo-express
    restart: always
    ports:
      - 8101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: g)2gH4G)4(3(
      ME_CONFIG_MONGODB_URL: mongodb://root:g)2gH4G)4(3(@mongo:27017/
    depends_on:
      - mongo

  zol1:
    container_name: zol1
    build:
      context: .
      dockerfile: ./Dockerfile_zol1
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 5050:5050
    depends_on:
      - neo
    links:
      - neo
      
  zol2:
    container_name: zol2
    build:
      context: .
      dockerfile: ./Dockerfile_zol2
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 5051:5050
    depends_on:
      - zol3
    links:
      - neo
      - mongo

  zol3:
    container_name: zol3
    build:
      context: .
      dockerfile: ./Dockerfile_zol3
    restart: always
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - zol1
      - mongo
    links:
      - mongo

